# Generated by Django 6.0.3 on 2026-03-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Paste an image link here', max_length=500)),
                ('is_primary', models.BooleanField(default=False, help_text='Use this as the main image on product list')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
