# Generated by Django 6.0.3 on 2026-03-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('appliances', 'Appliances'), ('other', 'Other')], default='fashion', max_length=20),
        ),
    ]
