# Generated by Django 6.0.3 on 2026-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('fashion_men', 'Men'), ('fashion_women', 'Women'), ('electronics_headsets', 'Headsets'), ('electronics_laptops', 'Laptops'), ('electronics_accessories', 'Accessories'), ('mobiles_iphone', 'iPhone'), ('mobiles_samsung', 'Samsung'), ('mobiles_oppo', 'OPPO'), ('mobiles_nothing', 'Nothing'), ('mobiles_motorola', 'Motorola'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
